flyway.url=jdbc:postgresql://127.0.0.1:5432/prh
flyway.locations=/db/flyway/common,/db/flyway/data/dev,/db/flyway/data/prod,/db/flyway/migration
flyway.user=postgres
flyway.password=postgres
flyway.schemas=prh
flyway.placeholders.schema=prh
flyway.installedBy=PeripheralRobotHelper