ksuto.prh.database.name=prh
ksuto.prh.database.schema=public
ksuto.prh.database.login=postgres
ksuto.prh.database.password=postgres

# true | false
ksuto.prh.database.offline=false

ksuto.prh.peripherals.delay=100

# WINDOWED | FULLSCREEN
ksuto.prh.peripherals.screen=FULLSCREEN

ksuto.prh.peripherals.mouse.drag.delay=10
ksuto.prh.peripherals.mouse.drag.space=5
ksuto.prh.peripherals.keyboard.typing.delay=50

# true | false
ksuto.prh.seeker.saveCaptureOnNotFound=false